name: Container Info

on:
  push:
    paths:
      - ".github/workflows/dockerhub-info.yml"
      - "README.md"
      - "LICENSE"
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: '${{ github.repository }}'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Docker hub info
        uses: peter-evans/dockerhub-description@v4
        with:
          username: '${{ secrets.DOCKER_USER }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
          repository: '${{ github.repository }}'